baseURL: "https://jaairomacedo.github.io/" 
title: Jairo MacedoX
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: data/
          weight: 5 
        - name: Research
          url: papers/
          weight: 2
        - name: Portfolio
          url: courses/
          weight: 3
      #  - name: Data
        #  url: data/
        #  weight: 4 
       # - name: Blog
       #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: "I‚Äôm an economist with a Master‚Äôs degree from UFPE"
    author: Jairo Macedo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jairo Macedo
          subtitle: "üëãüèº Hey, I‚Äôm Jairo! Be welcome.\n\n\nüë®üèª‚Äçüíª I‚Äôm an economist with a Master‚Äôs degree from UFPE.\n\n\nüîç I'm interested in applied economics ‚Äî especially causal inference in agriculture, misallocation, and corporate finance ‚Äî and I like to spice things up with the occasional macro model.\n\n\nüìö I‚Äôm currently applying machine learning methods to problems in applied economics, with a focus on causal inference and forecasting.\n\n\nüíº I‚Äôve also worked in the corporate world, leading efforts in management, strategic planning, high-impact projects, and data-driven decision-making."
          
          imageUrl: "profile.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: papers/
            - name: Portfolio
              url: courses/
            - name: CV
              url: data/
           # - name: Books
           #   url: books/
           # - name: Tags
           #   url: tags/
           # - name: Archive
            #  url: archive/
           # - name: Blog
           #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Jairo_cv.pdf
        - name: Email
          url: mailto:jairo.macedo@ufpe.br
        - name: Linkedin
          url: https://www.linkedin.com/in/jairomacedo/
        - name: GitHub
          url: https://github.com/jaairomacedo
        - name: X
          url: https://x.com/_jairo
       # - name: Kaggle
       #   url: https://www.kaggle.com/jairomacedo
       # - name: YouTube
       #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
    #  - name: Zoom
      #    url: https://www.zoom.us/my/igelfeld
      #  - name: Location
      #    url: location/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jairo's homepage"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
